Documentation (demo 1 and comprehensive story(
openalto/ietf-hackathon pull request #44
Opened 2022-04-21 13:02 UTC by MattSlm

2022-04-25 08:36 UTC, fno2010 requested changes
Overall looks good to me. Just need some minor changes.

2022-04-25 08:36 UTC, fno2010 commented on docs/demo_1.md
> +# Demo 1: Alto-Based Replica Sorting
Can you change all the "Alto" to "ALTO"?

2022-04-25 08:36 UTC, fno2010 commented on docs/demo_1.md
> +| *Do not use sudo and make sure that the repos are present in the working directory (i.e. docker).*
It seems like `|` is not valid for the syntax of GitHub Flavor Markdown. I guess you want to use `>` instead?

2022-04-25 08:36 UTC, fno2010 commented on docs/demo_1.md
> +| Notice: This may take a few minutes to return.
I think you want to say "This may take a few minutes to finish"? Because the output should appear in stdout immediately.

2022-04-25 11:00 UTC, giralt commented
I would like to suggest that we create a folder 'ietf-113' (that is, ```ietf-hackathon/docs/ietf-113/```) and move the files hackathon_comprehensive_story.md and demo_1.md into it. Thanks.

2022-04-25 11:06 UTC, giralt commented on docs/hackathon_comprehensive_story.md
> +ATLAS [[2]](#2) experiment is one the four major scietific experiments at the Large Hadron Collider (LHC) [[3]](#3) at CERN [[4]](#4). Atlas generates more than one petabyte of data every day [[5]](#
Suggest adding articles and using in instead of at. Also scientific has a small typo:

*The* ATLAS experiment is one *of* the four major *scientific* experiments *in* the Large Hadron Collier at CERN.

2022-04-25 11:06 UTC, giralt commented on docs/hackathon_comprehensive_story.md
> +ATLAS [[2]](#2) experiment is one the four major scietific experiments at the Large Hadron Collider (LHC) [[3]](#3) at CERN [[4]](#4). Atlas generates more than one petabyte of data every day [[5]](#
unprecendentedly => unprecendented

2022-04-25 11:06 UTC, giralt commented on docs/hackathon_comprehensive_story.md
> +Rucio is built on top of Atlas storage systems to s**calably and efficiently manage the replication and archiving of the created data and administer accesses to the data**. "**One of the guiding prin
should be **scalably** instead of s**calably**? (with a bolded s too)

2022-04-28 13:44 UTC, MattSlm commented on docs/demo_1.md
> +# Demo 1: Alto-Based Replica Sorting
Done!

2022-04-28 14:00 UTC, MattSlm commented on docs/hackathon_comprehensive_story.md
> +Rucio is built on top of Atlas storage systems to s**calably and efficiently manage the replication and archiving of the created data and administer accesses to the data**. "**One of the guiding prin
Thank you @giralt. Changed at https://github.com/openalto/ietf-hackathon/blob/documentation/docs/hackathon_comprehensive_story.md 
**commit** https://github.com/openalto/ietf-hackathon/commit/c66ee0512cea33789544dd0f2e8db1c10f788ebf

2022-04-28 14:01 UTC, MattSlm commented on docs/hackathon_comprehensive_story.md
> +ATLAS [[2]](#2) experiment is one the four major scietific experiments at the Large Hadron Collider (LHC) [[3]](#3) at CERN [[4]](#4). Atlas generates more than one petabyte of data every day [[5]](#
Thank you @giralt. resolved

2022-05-02 12:40 UTC, giralt commented on docs/hackathon_comprehensive_story.md
> +## Conclusoin
Typo: Conclusion

@MattSlm, can I suggest that you run the spell checker on the whole text? thanks.

2022-05-26 12:29 UTC, MattSlm commented on docs/hackathon_comprehensive_story.md
> +## Conclusoin
Done!

2022-05-26 12:54 UTC, MattSlm commented
> Thanks @MattSlm for pushing this PR. I would like to suggest that we create a folder 'ietf-113' (that is, `ietf-hackathon/docs/ietf-113/`) and move the files hackathon_comprehensive_story.md and demo_1.md into it. Thanks.

Done!

2022-05-26 13:08 UTC, giralt approved these changes

2022-06-09 13:55 UTC, fno2010 commented
@MattSlm Before we merge this PR, I hope you can go throughput all the changed files to fix this simple typo: Alto -> ALTO. I believe this typo still appears 6 times. I'm OK with the other parts. Thanks :)

2022-06-09 14:05 UTC, merged